name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install pnpm
      run: npm install -g pnpm
    - run: pnpm install
    - name: Compile Contracts
      run: pnpm exec hardhat compile
    - name: Run Tests
      run: pnpm exec hardhat test --network hardhat
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install pnpm
      run: npm install -g pnpm
    - run: pnpm install
    - name: Compile Contracts
      run: pnpm exec hardhat compile
    - name: Deploy Smart Contract
      run: pnpm exec hardhat run scripts/deploy.js --network sepolia
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
    - name: Update Contract Address
      run: |
        CONTRACT_ADDRESS=$(cat src/artifacts/contracts/MoodNFT.sol/contractAddress.txt)
        echo "NEXT_PUBLIC_CONTRACT_ADDRESS=$CONTRACT_ADDRESS" >> $GITHUB_ENV
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./
        vercel-args: '--prod'
      env:
        NEXT_PUBLIC_CONTRACT_ADDRESS: ${{ env.NEXT_PUBLIC_CONTRACT_ADDRESS }}
